### PR TITLE
Check for empty auth info as well as null.

### PR DESCRIPTION
**Pull request by nickmbailey**

### CODE REVIEW

**Comment by joekiller** [comment]
@nickmbailey maybe squash and rebase?

**Comment by nickmbailey** [comment]
This was purposely branched from 1.3.0 in case it can go into a 1.3.1 patch release, but I'm happy to rebase against master if thats needed. Also happy to squash to a new branch and create a new PR, but any reason not to just use the github squash+merge feature?

**Comment by danielcompton** [comment]
This has been merged in as 1.3.1-alpha3.

**Comment by rymndhng** [comment]
Hey @danielcompton the PR appears to not have been merged (I don't see it in master).

**Comment by danielcompton** [comment]
Sorry, I've pushed it now.

**Comment by joekiller** [comment]
We've tested 1.3.1-alpha3 and is good for us.

**Pull request closed without merging**
